### ISSUE TITLE
依赖安装不上

### ISSUE THREAD

**Issue by 3272539883** [MoMingRose/QLAutomateTasks#1]
![1000005287](https://github.com/MoMingRose/QLAutomateTasks/assets/72239269/8a89a372-d841-4a87-a6f4-8ce673259afa)
![1000005288](https://github.com/MoMingRose/QLAutomateTasks/assets/72239269/4f8eead6-0bc9-4bd2-8891-6a35afb848eb)

**Comment by MoMingRose** [comment]
> ![1000005287](https://private-user-images.githubusercontent.com/72239269/309520992-8a89a372-d841-4a87-a6f4-8ce673259afa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzU5MDksIm5iZiI6MTcwOTQzNTYwOSwicGF0aCI6Ii83MjIzOTI2OS8zMDk1MjA5OTItOGE4OWEzNzItZDg0MS00YTg3LWE2ZjQtOGNlNjczMjU5YWZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NTQzMGQ4YWQ2N2Q3YWU4NTIxMjMwODhhNmFiNGVlN2VmZWQ0MTU1YWE2NGIyNTMzMmYwZDQ0MTNiYjk2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_-f9-wCEKssgNJZoocttLp4aYMjFPt7J94LCzhUP_4) ![1000005288](https://private-user-images.githubusercontent.com/72239269/309521001-4f8eead6-0bc9-4bd2-8891-6a35afb848eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzU5MDksIm5iZiI6MTcwOTQzNTYwOSwicGF0aCI6Ii83MjIzOTI2OS8zMDk1MjEwMDEtNGY4ZWVhZDYtMGJjOS00YmQyLTg4OTEtNmEzNWFmYjg0OGViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDVhNGNjMDczY2UyMjMzNmUxMmRkYmJlZGRjZWM1MjA2ZWI1MzkwZjI0ZjUxOWVjOWFiNTA5NGJiYjcyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ozmjbT32zR66B2BedVzLaHum79klDTke2qwePF7brI)

试着重新更新订阅下，`脚本管理`的`utils`目录下必须出现`project_utils.py`文件
![image](https://github.com/MoMingRose/QLAutomateTasks/assets/108046002/5d0abddb-cd1b-457d-b2ad-0ea44296421c)

**Comment by 3272539883** [comment]
我脚本在scripts里，依赖在repo里，移过来就解决了，感谢🙏
