### ISSUE TITLE
大佬，安装依赖显示这个错误是什么原因呢

### ISSUE THREAD

**Issue by 591047593** [MoMingRose/QLAutomateTasks#2]
开始安装依赖 pydantic，开始时间 2024-03-13 21:49:34

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pydantic
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e5/f3/8296f550276194a58c5500d55b19a27ae0a5a3a51ffef66710c58544b32d/pydantic-2.6.4-py3-none-any.whl (394 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.9/394.9 kB 479.8 kB/s eta 0:00:00
Collecting annotated-types>=0.4.0 (from pydantic)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.16.3 (from pydantic)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/3f/65dbe5231946fe02b4e6ea92bc303d2462f45d299890fd5e8bfe4d1c3d66/pydantic_core-2.16.3.tar.gz (368 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

依赖安装失败，结束时间 2024-03-13 21:50:09，耗时 35 秒

**Comment by MoMingRose** [comment]
> 开始安装依赖 pydantic，开始时间 2024-03-13 21:49:34
> 
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple查看索引：https://pypi.tuna.tsinghua.edu.cn/simple Collecting pydantic  收集花饰 Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e5/f3/8296f550276194a58c5500d55b19a27ae0a5a3a51ffef66710c58544b32d/pydantic-2.6.4-py3-none-any.whl (394 kB) 下载 https://pypi.tuna.tsinghua.edu.cn/packages/e5/f3/8296f550276194a58c5500d55b19a27ae0a5a3a51ffef66710c58544b32d/pydantic-2.6.4-py3-none-any.whl (394 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.9/394.9 kB 479.8 kB/s eta 0:00:00 ──────────────────────────────────────────────────────────────── 394.9/394.9 kB 479.8 kB/s 预计时间 0:00: 00 Collecting annotated-types>=0.4.0 (from pydantic) 收集带注释的类型>=0.4.0（来自 pydantic） Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl (12 kB) 使用缓存的 https://pypi.tuna.tsinghua.edu.cn/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl (12 kB) Collecting pydantic-core==2.16.3 (from pydantic) 收集 pydantic-core==2.16.3 （来自 pydantic） Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/3f/65dbe5231946fe02b4e6ea92bc303d2462f45d299890fd5e8bfe4d1c3d66/pydantic_core-2.16.3.tar.gz (368 kB) 使用缓存的 https://pypi.tuna.tsinghua.edu.cn/packages/77/3f/65dbe5231946fe02b4e6ea92bc303d2462f45d299890fd5e8bfe4d1c3d66/pydantic_core-2.16.3.tar.gz (368 kB) Installing build dependencies: started 安装构建依赖项：已开始 Installing build dependencies: finished with status 'done' 安装构建依赖项：已完成，状态为“完成” Getting requirements to build wheel: started 获取构建轮子的要求：开始 Getting requirements to build wheel: finished with status 'done' 获取构建轮子的要求：已完成，状态为“完成” Preparing metadata (pyproject.toml): started 准备元数据（pyproject.toml）：开始 Preparing metadata (pyproject.toml): finished with status 'error' 准备元数据（pyproject.toml）：已完成状态“错误” error: subprocess-exited-with-error 错误：子进程退出并出现错误
> 
> × Preparing metadata (pyproject.toml) did not run successfully.× 准备元数据 (pyproject.toml) 未成功运行。 │ exit code: 1 │ 退出代码：1 ╰─> [6 lines of output] ╰─>【6行输出】
> 
> ```
>   Cargo, the Rust package manager, is not installed or is not on PATH.
>   This package requires Rust and Cargo to compile extensions. Install it through
>   the system's package manager or via https://rustup.rs/
>   
>   Checking for Rust toolchain....
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.注意：此错误源自子进程，并且可能不是 pip 的问题。 error: metadata-generation-failed 错误：元数据生成失败
> 
> × Encountered error while generating package metadata.× 生成包元数据时遇到错误。 ╰─> See above for output. ╰─> 输出见上文。
> 
> note: This is an issue with the package mentioned above, not pip.注意：这是上面提到的包的问题，​​而不是 pip 的问题。 hint: See above for details. 提示：详细信息请参见上文。
> 
> 依赖安装失败，结束时间 2024-03-13 21:50:09，耗时 35 秒

抱歉，我也是第一次见这种报错，不过我可以提供一些参考信息给你排错：

下面是我的使用环境
青龙面板：2.17.2
python3开发环境：3.10

我在requirements.txt中定义的pydantic版本是`pydantic==2.6.2`
根据官网的提示，它被支持在python3.8+以上的版本安装

希望以上的信息对你有用，如果你已经有了解决方法，还望能够分享出来给我们参考

**Comment by 591047593** [comment]
尝试更换青龙拉库解决了，
一直拉取得alpine版本
更换debian 版本就解决了     具体原因 不太明白    可能和安装ddddocr库类似

**Comment by MoMingRose** [comment]
> 尝试更换青龙版本解决了， 一直拉取得alpine版本 更换debian 版本就解决了 具体原因 不太明白 可能和安装ddddocr库类似

感谢解答！
